taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
taskkill /f /im abrir.exe
